version: "3.9"

services:

  worker:

    build: .

    environment:

      - TG_BOT_TOKEN=${TG_BOT_TOKEN}

      - APP_ID=${APP_ID}

      - API_HASH=${API_HASH}

      - AUTH_USERS=${AUTH_USERS}

      - TG_USER_SESSION=${TG_USER_SESSION}

      - DB_URI=${DB_URI}
